### ISSUE TITLE
generate fr and de - 1981

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/ontap-tools-vmware-vsphere-910#4]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by netapp-gudugunti** [comment]
de-de site is down.
Re-running the workflow.

**Comment by netapp-gudugunti** [comment]
fr-fr site is up.
de-de site is down after the re-run.
Build is successful with annotations.

**Comment by ntap-bmegan** [comment]
@dmajones - Can you look at the GH Pages for German? The dictionary and files are back, but it's not configured and there's no gh-pages branch for me to assign to it.

**Comment by ntap-bmegan** [comment]
Rebuild was successful.

**Comment by dmajones** [comment]
Sites (fr-fr& de-de) are up and running.
Total TOT: 7 minutes.
